import { privacyPolicyVersion } from "../../utils/constants";
import { LegalDocument } from "./LegalDocument";

export default function PrivacyPolicy() {
  return <LegalDocument data={{
    title: "Privacy Policy",
    version: privacyPolicyVersion,
    definitions: [
      {
        title: "Privacy Policy",
        description: "This agreement, defining the privacy policy that applies to Organisers and Customers."
      },
      {
        title: "Customer",
        description: "An individual who books tickets for an Event using our Platform."
      },
      {
        title: "Organiser",
        description: "Supplier of Event services to customers.This could be a promoter, venue, performer, society or organisation.They are responsible for marketing the event, and supplying the promised services to Customers."
      },
      {
        title: "User",
        description: "Organisers, Customers and third parties using our Platform."
      },
      {
        title: "Personal Data",
        description: "Information that can be associated with or which relates to a person and/or could be used to identify a person."
      },
      {
        title: "Non-Personal Data",
        description: "Information that does not relate to a person and/or cannot be used to identify a person."
      },
      {
        title: "We, us, our",
        description: "Kanjipay LTD trading as Mercado."
      },
      {
        title: "You, your",
        description: "The User who is agreeing to these terms."
      },
      {
        title: "Applications",
        description: "Mercado mobile applications, webpages, application programming interfaces, and subdomains."
      },
      {
        title: "Services",
        description: "Mercado's platform, features and offerings, available online via its Applications and offline including without limitation, RFID, entry management, sponsorship and marketing or distribution services."
      },
      {
        title: "User Generated Content",
        description: "Images, text and other content uploaded by Users to the Platform."
      },
      {
        title: "GDPR",
        description: "the General Data Protection Regulation (EU) 2016/679."
      },
    ],
    sections: [
      {
        title: "Who we are",
        clauses: [
          "Mercado is an events organisation and ticketing platform. We are incorporated as Kanjipay Ltd, registered at 8B Mitchison Rd, London, N1 3NG.",
          "Kanjipay Ltd is the is the responsible party with respect to Personal Data collected through the Services. Kanjipay Ltd is also the representative for European data protection law purposes.",
          "Our support email is team@mercadopay.co. Please contact us if you have any questions regarding this Privacy Policy.",
        ]
      },
      {
        title: "Our privacy statement",
        clauses: [
          'This Privacy Policy sets forth our policy with respect to Personal Data that is collected from Users on or through the Services. This policy also covers personal data collected from Mercado sales customers and prospects. We take the privacy of your Personal Data seriously. Because of that, we have created this Privacy Policy. Please read this Privacy Policy as it includes important information regarding your Personal Data and other information.',
          `When you interact with the Services, we may collect Non-Personal Data. The limitations and requirements in this Privacy Policy on our collection, use, disclosure, transfer and storage/retention of Personal Data do not apply to Non-Personal Data.`
        ]
      },
      {
        title: "Personal Data That We Collect",
        clauses: [
          'When you use or interact with us through the Services or engage with Mercado as a sales customer or prospect, we may collect Personal Data. Sometimes this will be on our own behalf and other times this will be on behalf of an Organiser using our Services to run an event. This is an important distinction for purposes of certain data protection laws and is explained in more detail below.',
          'Information you provide to us: For all Users we collect Personal Data when you voluntarily provide such information to the Services, such as when you register for access to the Services, contact us with inquiries, respond to one of our surveys or browse or use certain parts of the Services. The Personal Data we may collect includes without limitation your name, address, email address and any other information that you choose to provide and/or that enables Users to be personally identified. Information we automatically collect: We also automatically collect certain technical data that is sent to us from the computer, mobile device and/or browser through which you access the Services ("Automatic Data"). Automatic Data, includes without limitation, a unique identifier associated with your access device and/or browser (including, for example, your Internet Protocol (IP) address) characteristics about your access device and/or browser, statistics on your activities on the Services, information about how you came to the Services and data collected through Pixel Tags, Local Shared Objects, Web Storage and other similar technologies. When you register for the Services or otherwise submit Personal Data to us, we may associate other Non-Personal Data (including Non-Personal Data we collect from third parties) with your Personal Data. At such instance, we will treat any such combined data as your Personal Data until such time as it can no longer be associated with you or used to identify you.',
          'If you are an Organiser we will collect additional Personal Data from you. Information you provide to us: In some cases, we may collect your credit card information (e.g., your credit card number and expiration date, billing address, etc.), some of which may constitute Personal Data, to secure certain payments. In addition, if you use our payment processing services, we will collect financial information from you (e.g., your bank account information or an address to send checks) as necessary to facilitate payments and information required for tax purposes (e.g., your taxpayer identification number). Information we obtain from other sources: We may also collect or receive Personal Data including your name, email address and other contact information from third party sources, such as third party websites and marketing partners, your bank, our payment processing partners and credit reporting agencies.',
          'If you are a Customer we will collect additional Personal Data from you, sometimes for our own purposes and other times on behalf of an Organiser.',
          'Information you provide via Mercado Properties or Applications: If you register for a paid event, you will provide financial information (e.g., your credit card number and expiration date, billing address, etc.) some of which may constitute Personal Data. In addition, Organisers can set up event registration pages to collect virtually any information from Customers in connection with registration for an Organiser\'s event listed on the Services. Mercado does not control an Organiser\'s registration process nor the Personal Data that they collect. When you register for, or otherwise provide information to Mercado in conjunction with an Organiser event or activity, whether that information is yours or a third party\'s, in connection with a purchase, registration, or transfer, that Organiser will receive and may use the information you provide.',
          'Information we obtain from other sources: We may also collect or receive Personal Data from third party sources, such as Organisers, other Customers, social media or other third party integrations, your credit card issuing bank, our payment processing partners or other third parties.',
          'If you engage with the Mercado sales team we may collect the following: your name, email, address, phone number, and other professional contact information. If you engage with the sales team and consent to recording a meeting, the sales team may collect audio and/or video recordings of you.',
        ]
      },
      {
        title: "How we use your personal data",
        clauses: [
          'We collect and use the Personal Data we collect in a manner that is consistent with this Privacy Policy, and applicable privacy laws. We may use the Personal Data as follows:',
          'If you provide Personal Data for a certain purpose, we may use the Personal Data in connection with the purpose for which it was provided. For instance, if you contact us by email, we will use the Personal Data you provide to answer your question or resolve your problem and will respond to the email address from which the contact came.',
          'If you provide Personal Data in order to obtain access to or use of the Services or any functionality thereof, we will use your Personal Data to provide you with access to or use of the Services or functionality and to analyse your use of such Services or functionality. For instance, if you supply Personal Data relating to your identity or qualifications to use certain portions of the Services, we will use that information to make a decision as to granting you access to use such Services and to assess your ongoing qualification to use such Services.',
          'We may use your Personal Data for internal business purposes, including without limitation, to help us improve the content and functionality of the Services, to better understand our Users, to improve the Services, to protect against, identify or address wrongdoing, to enforce our Terms of Service, to manage your account and provide you with customer service, and to generally manage the Services and our business.',
          'We may use your Personal Data for our marketing and advertising purposes, including (without limitation) by email, SMS marketing, display media, and targeting other devices (such as tablets, mobile devices and televisions). We do this in order to inform you about services or events we believe might be of interest to you, develop promotional or marketing materials and display Mercado or event-related content and advertising on or off the Services that we believe might be of interest to you. We may also do this on behalf of an Organiser, for example where your prior interactions with an Organiser suggest you may be interested in a particular type of event. See "Opt Out from Electronic Communications" below on how to opt out of various Mercado marketing communications.',
          'You may see advertisements for our Services on third party websites, including on social media platforms. We also provide Organisers with tools to help them display advertisements for their events on third party websites and social media platforms. Where you see an advertisement on a third party website or social media platform, this may be because we or the Organiser engaged the third party or social media platform to show the advertisement to Users, or to others who have similar attributes to our Users. In some cases, this involves sharing your email address or other contact details with the third party or social media platform so that they can identify you as one of our Users, or identify other individuals with similar attributes to you in order to show them advertisements for our Services (or for our Organiser’s events). If you no longer want your Personal Data to be used for these purposes please contact us at team@mercadopay.co. In the case of an Organiser’s advertising, you may need to contact the Organiser directly.',
          'We allow Organisers to use our email tools to contact Customers for their current and past events, so you may receive emails from our system that originate with such Organisers and that we send on their behalf. If you registered for an event on the Services, your email address is available to that Organiser. However, Organisers may also import the email addresses they have from external sources and send communications through the Services to those email addresses, and we will deliver those communications to those email addresses on the Organiser\'s behalf. The Organiser and not Mercado is responsible for sending these emails. See "Opt Out from Electronic Communications" below on how to opt out of Organiser-initiated communications.',
          'We sometimes make inferences about the type of events or activities you may be interested in. We may use these inferences to help target advertising or customise recommendations to you, including on behalf of Organisers. We may do this on an aggregated or generalized basis. For instance, we may determine that our users who attend many comedy events also often attend or show interest in endurance-related events or content. We may direct (or assist in directing) content or recommendations related to both comedy and endurance to those Users.',
          'If we intend to use any Personal Data in any manner that is not consistent with this Privacy Policy, you will be informed of such anticipated use prior to or at the time the Personal Data is collected or we will obtain your consent subsequent to such collection but prior to such use.',
          'In an ongoing effort to understand and serve our Users better, we often conduct research on our customer demographics, interests and behavior based on Personal Data and other information that we have collected. This research is typically conducted on an aggregate basis only that does not identify you. Once Personal Data is in an aggregated form, for purposes of this Privacy Policy, it becomes Non-Personal Data.',
        ]
      },
      {
        title: "How We Disclose And Transfer Your Personal Data",
        clauses: [
          'We are not in the business of selling your Personal Data. We consider this information to be a vital part of our relationship with you. Therefore, we will not sell your Personal Data to third parties, including third party advertisers. There are certain circumstances in which we may disclose, transfer or share your Personal Data with certain third parties without further notice to you, as set forth in this Privacy Policy.',
          'As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganisation, dissolution or similar event, Personal Data may be part of the transferred assets. We may also disclose your Personal Data in the course of due diligence for such an event. You acknowledge and agree that any successor to or acquirer of Mercado (or its assets) will continue to have the right to use your Personal Data and other information in accordance with the terms of this Privacy Policy.',
          'We may also share your Personal Data with our parent companies, subsidiaries and/or affiliates for purposes consistent with this Privacy Policy. Our parent companies, subsidiaries and affiliates will be bound to maintain that Personal Data in accordance with this Privacy Policy.',
          'We may share your Personal Data with our contractors and service providers who process Personal Data on behalf of Mercado to perform certain business-related functions. These companies include our marketing agencies, online advertising providers, data enhancement and data services providers, database service providers, backup and disaster recovery service providers, email service providers, payment processing partners, customer support, tech support, hosting companies and others. When we engage another company to perform such functions, we may provide them with information, including Personal Data, in connection with their performance of such functions.',
          'In addition, when you register for an event, sign up for communications, enter a contest, or otherwise input your Personal Data (such as through a web form) to communicate with an Organiser or participate in an Organiser event, that Organiser will receive that information. For instance, if you input your name and email address into a web form for an Organiser offer, activity or event, the Organiser will receive that information. The Organiser may then send you marketing or other communications, which may be subject to its own, separate privacy policy. Likewise, if you provide your mobile phone number, you may receive information messages related to the service, event, activity or information in which you’ve expressed interest.',
          'When you purchase tickets to, register for or donate to an event, transfer an event ticket or registration to another person, enter a contest, or otherwise input your Personal Data (such as through a web form), or otherwise communicate with an Organiser, or participate in or express interest in an Organiser or Organiser event or activity, that Organiser will receive the information you provide, including your Personal Data, and where a ticket or registration is transferred, the Personal Data of the transferee as well. Other third parties that are involved in or on whose behalf an event or activity is promoted, may receive that Personal Data as well. For example, as to fundraising pages, we may provide your Personal Data both to the Organiser charity of the fundraising page and the Organiser of the event to which the fundraising page is linked. In some instances, an Organiser may appoint a third party, which may or may not be affiliated with the Organiser, to create an event or fundraising page on its behalf (we call these third parties ("Third Party Organisers"). For example, and without limitation, a concert venue (the Organiser, in this case) may allow third party promoters or production companies (the Third Party Organisers) to create events that will be hosted at the Organiser\'s venue using its Mercado account. In that case, we may provide your Personal Data to the Third Party Organisers on behalf of the Organisers. The same is true for contests and sweepstakes: we may provide your Personal Data to both the Organiser promoting the contest or sweepstakes, and any legal sponsor of the contest or sweepstakes(such as a brand sponsor).We are not responsible for the actions of these Organisers, or their Third Party Organisers(or other downstream recipients of your Personal Data), with respect to your Personal Data. It is important that you review the applicable policies of the Organisers, and if applicable and available, their appointed Third Party Organisers, of an event(and the related fundraising page, if applicable) before providing Personal Data or other information in connection with that event or related fundraising page. Similarly, if you are a member of an Organiser\'s organisation within Mercado, your Personal Data will be available to the Organiser and shared with those Third Party Organisers granted permission by the Organiser to view all members of the Organiser\'s organisation.',
          'You can connect your Mercado account to your accounts on third party services like Facebook, in which case we may collect, use, disclose, transfer and store/retain information relating to your account with such third party services in accordance with this Privacy Policy. For example, if you connect with Facebook, we store your Facebook id, first name, last name, email, location, friends list and profile picture and use them to connect with your Facebook account to provide certain functionality on the Services, like recommending events that your Facebook friends are interested in and sharing the events you are interested in, or attending, with certain groups of people like your Facebook friends.',
          'In addition, when you “like” or “follow” us on Facebook, Instagram, Twitter or other social media sites (to the extent we provide that capability), we may collect some information from you including your name, email address, and any comments or content you post relevant to us. We likewise may collect your information if you sign up for one of our promotions or submit information to us through social media sites.',
          'Mercado’s own website may contain links to Facebook as well, such as through the Facebook “Like” or “Share” button or other social plug-ins. When you interact with these features and links, your browser will establish a direct link with the Facebook servers, and Facebook will receive information about your browser and activity, and may link it to your Facebook user account. For more information about how Facebook uses data, please see Facebook’s own policies.',
          'In addition, if you are a member of Facebook (or another social media platform), and you provide Personal Data to an Organiser, the Organiser may use that Personal Data to send you advertising and offers through Facebook (or another social media) platform, including when you are on Facebook or another social media platform. The Organiser may use tool thats we provide and may also work with third parties to enable this data integration and advertising. Facebook and other social media platforms may provide a way to opt out of this type of advertising. Please review their user settings and support pages to learn more about how they help you to manage privacy and marketing choices.',
          'Mercado may provide you with opportunities to contract directly with third parties, and/or to integrate with third party services or applications, through our platform. In such instances, we will disclose your Personal Data to other entities in order to fulfill a request by you, or to provide services you have requested.',
          'We may disclose your Personal Data if required to do so by law in order to (for example) respond to a subpoena or request from law enforcement, a court or a government agency (including in response to public authorities to meet national security or law enforcement requirements), or in the good faith belief that such action is necessary to (a) comply with a legal obligation, (b) protect or defend our rights, interests or property or that of third parties, (c) prevent or investigate possible wrongdoing in connection with the Services, (d) act in urgent circumstances to protect the personal safety of Users of the Services or the public, or (e) protect against legal liability.',
        ]
      },
      {
        title: "How We Store Your Personal Data",
        clauses: [
          'We may store Personal Data itself or such information may be stored by third parties to whom we have transferred it in accordance with this Privacy Policy. We take what we believe to be reasonable steps to protect the Personal Data collected via the Services from loss, misuse, unauthorised use, access, inadvertent disclosure, alteration and destruction. However, no network, server, database or Internet or email transmission is ever fully secure or error free. Therefore, you should take special care in deciding what information you send to us electronically. Please keep this in mind when disclosing any Personal Data.',
        ]
      },
      {
        title: "How You Can Access, Update, Correct or Delete Your Personal Data",
        clauses: [
          "You can access or delete your Personal Data stored by us. If you are a registered User, you can do this by logging in and visiting the Account Settings page to download a copy of your Personal Data in machine readable form and/or delete your Personal Data. You can also edit some of your Personal Data directly through your account. In certain cases, you can ask us to correct and update any inaccurate Personal Data using the contact information below, and we will consider your request in accordance with applicable laws.",
          "If a Customer initiates a data deletion request, Mercado is authorised to delete or anonymize Personal Data of the requesting Customer from the Services even if that means removing its availability to the Organiser through the Services. However, if you are a Customer, you understand that even if Mercado deletes or anonymizes your Personal Data upon your request or pursuant to this Policy, your Personal Data may still be available in the Organiser's own databases if transmitted to the Organiser prior to Mercado receiving or taking action on any deletion or anonymization activity.",
          "Unregistered Users may also access, update, correct or delete Personal Data and exercise these rights using the contact information below. We will consider and respond to all requests in accordance with applicable law."
        ]
      },
      {
        title: "How Long We Retain Your Personal Data",
        clauses: [
          'We may retain your Personal Data as long as you are registered to use the Services. You may delete your account by visiting the Account Settings page. However, we may retain Personal Data for an additional period as is permitted or required under applicable laws. Even if we delete your Personal Data it may persist on backup or archival media for an additional period of time for legal, tax or regulatory reasons or for legitimate and lawful business purposes. For sales customers and prospects, we retain your data as long as we maintain a relationship with you and for a limited period of thereafter as necessary to meet business and legal requirements.',

        ]
      },
      {
        title: "Your Choices",
        clauses: [
          'You can browse the Services without providing any Personal Data (other than Automatic Data to the extent it is considered Personal Data under applicable laws) or with limiting the Personal Data you provide. If you choose not to provide any Personal Data or limit the Personal Data you provide, you may not be able to use certain functionality of the Services. For instance, in order to buy tickets as a Customer, your name and email address will be required by the Organiser.',
          'Where it is in accordance with your marketing preferences, Mercado may send you electronic communications marketing or advertising the Services themselves or events on the Services, to the extent you have registered for the Services or purchased a ticket and/or registration to an event listed on the Services. You can also "opt out" of receiving these electronic communications by clicking on the "Unsubscribe" link at the bottom of any such electronic communication. In addition, you may also manage your email preferences at any time by logging in (or signing up and then logging in).',
          'Organisers may use our email tools to send electronic communications to those on their email subscription lists, including Customers who have registered for their events on the Services in the past. Although these electronic communications are sent through our system, Mercado does not determine the content or the recipients of these electronic communications. Organisers are required to use our email tools only in accordance with all applicable laws. Mercado provides an "Unsubscribe" link on each of these emails, which allows recipients to "opt out" of electronic communications from the particular Organiser.',
          'If you connect your Facebook account or sign up for other social media integrations whose product features include social notifications (i.e., updates on what your friends are doing on the Services), you will receive these social notifications. You can manage these social notifications by toggling your social settings to private or disconnecting such integration.',
          'Certain electronic communications from Mercado are responsive to your requests. For instance, if you are a Customer, we must email you your ticket or registration on behalf of the Organiser when you purchase such ticket or registration. As a further example, if you email our customer support department, we will return your email. Notwithstanding any unsubscribe election that you have made, you will still receive these transactional or responsive emails. You can stop receiving these types of emails only by contacting us. By electing to stop receiving all electronic communications from us or through our system, you will no longer receive any updates on events you have created (including payout issues) or on events you are registered to attend (including emails with your tickets). We do not recommend that you do this unless you plan to no longer use the Services, are not currently registered for an event, are not currently organising an event, and will have no need to receive further communications from us or through our system.',
          'It may take up to forty-eight (48) hours for us to process an unsubscribe request. Even after you opt out of all electronic communications, we will retain your Personal Data in accordance with this Privacy Policy, however, we will no longer use it to contact you. However, Organisers who have received your Personal Data in accordance with this Privacy Policy may still use that Personal Data to contact you in accordance with their own privacy policies, but they may not use our system to do so.',
          'We currently do not participate in any "Do Not Track" frameworks that would allow us to respond to signals or other mechanisms from you regarding the collection of your Personal Data.',
        ]
      },
      {
        title: "Exclusions",
        clauses: [
          'This Privacy Policy does not apply to any Personal Data that you provide to another User or visitor through the Services or through any other means, including to Organisers on event pages or information posted by you to any public areas of the Services.',
          'This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us (the "Third Party Sites"). The policies and procedures we described here do not apply to the Third Party Sites. The links from the Services do not imply that we endorse or have reviewed the Third Party Sites. We suggest contacting those sites directly for information on their privacy policies.',
          'We do not knowingly collect Personal Data from children under the age of thirteen (13). If you are under the age of thirteen (13), please do not submit any Personal Data through the Services. We encourage parents and legal guardians to monitor their children\'s Internet usage and to help enforce our Privacy Policy by instructing their children never to provide Personal Data through the Services without their permission. If you have reason to believe that a child under the age of 13 has provided Personal Data to us through the Services, please contact us and we will endeavor to delete that information from our databases.',
        ]
      },
      {
        title: "International Privacy Laws",
        clauses: [
          'If you are visiting the Services from outside the United Kingdom, please be aware that you are sending information (including Personal Data) to the United Kingdom where our servers are located. That information may then be transferred within the United Kingdom or back out of the United Kingdom to other countries outside of your country of residence, depending on the type of information and how it is stored by us. These countries (including the United Kingdom) may not necessarily have data protection laws as comprehensive or protective as those in your country of residence; however, our collection, storage and use of your Personal Data will at all times continue to be governed by this Privacy Policy.'
        ]
      },
      {
        title: "Changes To This Privacy Policy",
        clauses: [
          'The Services and our business may change from time to time. As a result, at times it may be necessary for us to make changes to this Privacy Policy. We reserve the right, in our sole discretion, to update or modify this Privacy Policy at any time (collectively, "Modifications"). Modifications to this Privacy Policy will be posted to the Site with a change to the "Updated" date at the top of this Privacy Policy. In certain circumstances Mercado may, but need not, provide you with additional notice of such Modifications, such as via email or with in-Service notifications. Modifications will be effective thirty (30) days following the "Updated" date or such other date as communicated in any other notice to you.',
          'Please review this policy periodically, and especially before you provide any Personal Data. This Privacy Policy was updated on the date indicated above. Your continued use of the Services following the effectiveness of any Modifications to this Privacy Policy constitutes acceptance of those Modifications. If any Modification to this Privacy Policy is not acceptable to you, you should cease accessing, browsing and otherwise using the Services.'
        ]
      },
      {
        title: "Dispute Resolution",
        clauses: [
          'If you have a complaint about Mercado\'s privacy practises you should write to us at: Kanjipay Ltd, Privacy Officer, 8B Mitchison Rd, London, N1 3NG, or by email team@mercadopay.co. We will take reasonable steps to work with you to attempt to resolve your complaint.Residents of the EEA, Switzerland or the UK who believe that their information has not been processed in compliance with the Privacy Shield Principles may raise their complaints in a number of ways.For further information, please see our Privacy Shield Notice.',
          'EEA, SWITZERLAND AND UK ONLY The EU General Data Protection Regulation (GDPR) requires Mercado and Organisers using the Service to provide Users with more information about the processing of their Personal Data. Here is what you need to know:',
          'The GDPR requires us to tell you about the legal ground we\'re relying on to process any Personal Data about you. The legal grounds for us processing your Personal Data for the purposes set out in Section 4 above will typically be because: you provided your consent; it is necessary for our contractual relationship; the processing is necessary for us to comply with our legal or regulatory obligations; and/or the processing is in our legitimate interest as an event organising and ticketing platform (for example, to protect the security and integrity of our systems and to provide you with customer service, etc.).',
          'As Mercado is a global company, we may need to transfer your Personal Data outside of the country from which it was originally provided. This may be intra-group or to third parties that we work with who may be located in jurisdictions outside the EEA, Switzerland and the UK which have no data protection laws or laws that are less strict compared with those in Europe.',
          'Whenever we transfer Personal Data outside of the EEA, Switzerland or the UK, we take legally required steps to make sure that appropriate safeguards are in place to protect your Personal Data. This includes the use of Standard Contractual Clauses issued pursuant to Commission Implementing Decision (EU) 2021/914 of June 4, 2021 of the European Parliament and of the Council.',
          'We retain your Personal Data for as long as necessary to provide you with our Services, or for other important purposes such as complying with legal obligations, resolving disputes, and enforcing our agreements. If you have an account with us, we will typically retain your Personal Data for a period of ninety (90) days after you have requested that your account is closed or if it\'s been inactive for seven (7) years.',
          'Data protection law provides you with rights in respect of Personal Data that we hold about you, including the right to request a copy of the Personal Data, request that we rectify, restrict or delete your Personal Data, object to profiling and unsubscribe from marketing communications.',
          'For the most part, you can exercise these rights by logging in . If you can\'t find what you\'re looking for in the My Account page, please contact us using the contact information set out above. Please note that requests to exercise data protection rights will be assessed by us on a case-by-case basis. There may be circumstances where we are not legally required to comply with your request because of the laws in your jurisdiction or because of exemptions provided for in data protection legislation. If you have a complaint about how we handle your Personal Data, please get in touch with us to explain. If you are not happy with how we have attempted to resolve your complaint, you may contact the relevant data protection authority.',
          'EU data protection law makes a distinction between organisations that process Personal Data for their own purposes (known as "data controllers") and organisations that process personal data on behalf of other organisations (known as "data processors"). If you have a question or complaint about how your Personal Data is handled, these should always be directed to the relevant data controller since they are the ones with primary responsibility for your Personal Data.',
          'Mercado may act as either a data controller or a data processor in respect of your Personal Data, depending on the circumstances. For example, if you create an account with us to organise your events, Mercado will be a data controller in respect of the Personal Data that you provide as part of your account. We will also be a data controller of the Personal Data that we have obtained about the use of the Applications or Mercado Properties, which could relate to Organisers or Customers. We use this to conduct research and analysis to help better understand and serve Users of the Services as well as to improve our platform and provide you with more targeted recommendations about events we think may be of interest to you. However, if you register for an event as a Customer, we will process your Personal Data to help administer that event on behalf of the Organiser (for example, sending confirmation, promotional and feedback emails, processing payments, etc.) and to help the Organiser target, and understand the success of, their event and event planning (for example, providing event reports, using analytics to gain insights into the effectiveness of various sales channels, etc.). In these circumstances, Mercado merely provides the tools for Organisers; Mercado does not decide what Personal Data to request on registration forms, nor is it responsible for the continued accuracy of any Personal Data provided. Any questions that you may have relating to your Personal Data and your rights under data protection law should therefore be directed to the Organiser as the data controller, not to Mercado.'
        ]
      }
    ]
  }} />
}